# Generated by Django 4.2.1 on 2023-05-19 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0008_quizresult"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "verbose_name": "ответ на вопрос",
                "verbose_name_plural": "ответы на вопросы",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "вопрос", "verbose_name_plural": "вопросы"},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "тест", "verbose_name_plural": "тесты"},
        ),
        migrations.AlterModelOptions(
            name="quizresult",
            options={"verbose_name": "результат", "verbose_name_plural": "результаты"},
        ),
        migrations.AlterField(
            model_name="answer",
            name="is_correct",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="корректно?"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="main.question",
                verbose_name="вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="text",
            field=models.CharField(max_length=200, verbose_name="текст ответа"),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="main.quiz",
                verbose_name="тест",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="description",
            field=models.TextField(verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="title",
            field=models.CharField(max_length=100, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="date_taken",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="дата прохождения"
            ),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="main.quiz",
                verbose_name="тест",
            ),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="score",
            field=models.IntegerField(verbose_name="счёт"),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="total",
            field=models.IntegerField(verbose_name="итог"),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
